import {
  ApprovedContact,
  RestrictionSummary,
  AvailableSlot,
  FindByCriteriaResults,
  FindByCriteriaVisit,
  OfficialVisit,
} from '../@types/officialVisitsApi/types'
import { PrisonerRestrictionDetails } from '../@types/personalRelationshipsApi/types'
import { PrisonerScheduledEvents, ScheduledEvent } from '../@types/activitiesApi/types'

export const mockPrisoner = {
  firstName: 'John',
  lastName: 'Smith',
  prisonerNumber: 'A1337AA',
  prisonCode: 'MDI',
  dateOfBirth: '1989-06-01',
  cellLocation: '1-1-001',
  prisonName: 'Example Prison (EXP)',
}

export const mockTimeslots = [
  {
    visitSlotId: 1,
    timeSlotId: 1,
    prisonCode: 'MDI',
    dayCode: 'MON',
    dayDescription: 'Monday',
    visitDate: '2025-12-25',
    startTime: '08:00',
    endTime: '17:00',
    dpsLocationId: 'xxx',
    availableVideoSessions: 1,
    availableGroups: 1,
    availableAdults: 1,
    locationDescription: 'Mock Location',
  } as AvailableSlot,
]

export const mockScheduleTimeSlots = {
  prisonCode: 'MIC',
  prisonerNumbers: ['ABC123'],
  startDate: '2022-10-01',
  endDate: '2022-10-01',
  appointments: [
    {
      startTime: '08:00',
      endTime: '17:00',
      summary: 'Summary',
      eventType: 'APPOINTMENT',
      cancelled: false,
      inCell: true,
    },
  ] as ScheduledEvent[],
  courtHearings: [],
  visits: [],
  activities: [],
  externalTransfers: [],
  adjudications: [],
} as PrisonerScheduledEvents

export const mockScheduleEvents = [
  {
    startTime: '',
    endTime: '17:00',
    summary: 'Summary',
    eventType: 'APPOINTMENT',
    cancelled: false,
    inCell: true,
  },
  {
    startTime: '08:00',
    endTime: '17:00',
    summary: 'Summary',
    eventType: 'APPOINTMENT',
    cancelled: false,
    inCell: true,
  },
] as ScheduledEvent[]

export const sortedMockScheduleEvents = [
  {
    startTime: '08:00',
    endTime: '17:00',
    summary: 'Summary',
    eventType: 'APPOINTMENT',
    cancelled: false,
    inCell: true,
  },
  {
    startTime: '',
    endTime: '17:00',
    summary: 'Summary',
    eventType: 'APPOINTMENT',
    cancelled: false,
    inCell: true,
  },
] as ScheduledEvent[]

export const mockSchedule = [
  {
    id: 1,
    startTime: '08:00',
    endTime: '17:00',
    eventName: 'ROTL - out of prison',
    typeCode: 'ACT',
    typeDescription: 'Activity',
    locationCode: 'OUT',
    locationDescription: 'Out of prison',
  },
]

export const contactRestrictionSummary = {
  active: [
    {
      restrictionType: 'BAN',
      restrictionTypeDescription: 'Banned',
    },
    {
      restrictionType: 'CLOSED',
      restrictionTypeDescription: 'Closed visits only',
    },
  ],
  totalActive: 2,
  totalExpired: 1,
} as RestrictionSummary

export const mockOfficialVisitors = [
  {
    prisonerContactId: 1,
    contactId: 1,
    prisonerNumber: 'A1337AA',
    lastName: 'Smith',
    firstName: 'Abe',
    relationshipTypeCode: 'O',
    relationshipTypeDescription: 'Official',
    relationshipToPrisonerCode: 'SOL',
    relationshipToPrisonerDescription: 'Solicitor',
    isApprovedVisitor: true,
    isNextOfKin: false,
    isEmergencyContact: false,
    isRelationshipActive: true,
    currentTerm: true,
    isStaff: false,
    restrictionSummary: contactRestrictionSummary,
    dateOfBirth: '2006-01-01',
    street: '26 Acorn Road',
    area: 'Bushby',
    postcode: 'LE4 4NH',
    noFixedAddress: false,
    primaryAddress: true,
  },
  {
    prisonerContactId: 2,
    contactId: 2,
    prisonerNumber: 'A1337AA',
    lastName: 'Smith',
    firstName: 'Bertie',
    relationshipTypeCode: 'O',
    relationshipTypeDescription: 'Official',
    relationshipToPrisonerCode: 'POL',
    relationshipToPrisonerDescription: 'Police officer',
    isApprovedVisitor: true,
    isNextOfKin: false,
    isEmergencyContact: false,
    isRelationshipActive: true,
    currentTerm: true,
    isStaff: false,
    restrictionSummary: contactRestrictionSummary,
    dateOfBirth: '2006-01-01',
    street: '27 Acorn Road',
    area: 'Bushby',
    postcode: 'LE4 4NH',
    noFixedAddress: false,
    primaryAddress: true,
  },
  {
    prisonerContactId: 3,
    contactId: 3,
    prisonerNumber: 'A1337AA',
    lastName: 'Smith',
    firstName: 'Chris',
    relationshipTypeCode: 'O',
    relationshipTypeDescription: 'Official',
    relationshipToPrisonerCode: 'SOC',
    relationshipToPrisonerDescription: 'Social worker',
    isApprovedVisitor: true,
    isNextOfKin: false,
    isEmergencyContact: false,
    isRelationshipActive: true,
    currentTerm: true,
    isStaff: false,
    restrictionSummary: contactRestrictionSummary,
    dateOfBirth: '2006-01-01',
    street: '28 Acorn Road',
    area: 'Bushby',
    postcode: 'LE4 4NH',
    noFixedAddress: false,
    primaryAddress: true,
  },
] as ApprovedContact[]

export const mockSocialVisitors = [
  {
    prisonerContactId: 1,
    contactId: 1,
    prisonerNumber: 'A1337AA',
    lastName: 'Smith',
    firstName: 'Abe',
    relationshipTypeCode: 'S',
    relationshipTypeDescription: 'Social',
    relationshipToPrisonerCode: 'BRO',
    relationshipToPrisonerDescription: 'Brother',
    isApprovedVisitor: true,
    isNextOfKin: false,
    isEmergencyContact: false,
    isRelationshipActive: true,
    currentTerm: true,
    isStaff: false,
    restrictionSummary: contactRestrictionSummary,
    dateOfBirth: '2006-01-01',
    street: '26 Acorn Road',
    area: 'Bushby',
    postcode: 'LE4 4NH',
    noFixedAddress: false,
    primaryAddress: true,
  },
  {
    prisonerContactId: 2,
    contactId: 2,
    prisonerNumber: 'A1337AA',
    lastName: 'Smith',
    firstName: 'Bertie',
    relationshipTypeCode: 'S',
    relationshipTypeDescription: 'Social',
    relationshipToPrisonerCode: 'BRO',
    relationshipToPrisonerDescription: 'Brother',
    isApprovedVisitor: true,
    isNextOfKin: false,
    isEmergencyContact: false,
    isRelationshipActive: true,
    currentTerm: true,
    isStaff: false,
    restrictionSummary: contactRestrictionSummary,
    dateOfBirth: '2006-01-01',
    street: '27 Acorn Road',
    area: 'Bushby',
    postcode: 'LE4 4NH',
    noFixedAddress: false,
    primaryAddress: true,
  },
] as ApprovedContact[]

export const mockPrisonerRestrictions = [
  {
    prisonerRestrictionId: 3,
    prisonerNumber: 'A1337AA',
    restrictionType: 'CLOSED',
    restrictionTypeDescription: 'Closed',
    commentText: 'Closed visits only',
    effectiveDate: '2022-12-01',
    expiryDate: '2022-12-31',
    authorisedUsername: 'XXX',
    authorisedByDisplayName: 'XXX YYY',
    currentTerm: true,
    createdBy: 'XXX',
    createdTime: '2022-12-01 10:00',
  },
  {
    prisonerRestrictionId: 2,
    prisonerNumber: 'A1337AA',
    restrictionType: 'BAN',
    restrictionTypeDescription: 'Banned',
    commentText: 'Banned from all visits',
    effectiveDate: '2023-12-01',
    expiryDate: '2023-12-31',
    authorisedUsername: 'XXX',
    authorisedByDisplayName: 'XXX YYY',
    currentTerm: true,
    createdBy: 'XXX',
    createdTime: '2023-12-01 10:00',
  },
  {
    prisonerRestrictionId: 1,
    prisonerNumber: 'A1337AA',
    restrictionType: 'RESTRICTED',
    restrictionTypeDescription: 'Restricted',
    commentText: 'Not to contact Sarah Philips until 03/08/2026.',
    effectiveDate: '2017-10-17',
    authorisedUsername: 'XXX',
    authorisedByDisplayName: 'XXX YYY',
    currentTerm: true,
    createdBy: 'XXX',
    createdTime: '2017-10-17 10:00',
  },
] as PrisonerRestrictionDetails[]

export const mockFindByCriteriaVisit = {
  officialVisitId: 1,
  prisonCode: 'MDI',
  prisonDescription: 'Moorland (HMP & YOI)',
  visitStatus: 'SCHEDULED',
  visitStatusDescription: 'Completed',
  visitTypeCode: 'TELEPHONE',
  visitTypeDescription: 'Telephone',
  visitDate: '2022-12-23',
  startTime: '10:00',
  endTime: '11:00',
  dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
  locationDescription: 'Legal visits ward',
  visitSlotId: 1,
  staffNotes: 'Legal representation details',
  prisonerNotes: 'Please arrive 10 minutes early',
  visitorConcernNotes: 'string',
  numberOfVisitors: 3,
  completionCode: 'VISITOR_CANCELLED',
  completionDescription: 'string',
  createdBy: 'Fred Bloggs',
  createdTime: '2025-12-02 14:45',
  updatedBy: 'Jane Bloggs',
  updatedTime: '22025-12-04 09:50',
  prisoner: {
    ...mockPrisoner,
    dateOfBirth: '2025-12-19',
    cellLocation: 'string',
    middleNames: 'string',
    offenderBookId: 0,
    attendanceCode: 'string',
    attendanceCodeDescription: 'string',
  },
} as FindByCriteriaVisit

export const mockFindByCriteriaResults = {
  content: [mockFindByCriteriaVisit],
  page: {
    totalElements: 1,
    totalPages: 1,
    number: 0,
    size: 10,
  },
} as FindByCriteriaResults

export const mockVisitByIdVisit: OfficialVisit = {
  officialVisitId: 1,
  prisonCode: 'MDI',
  prisonDescription: 'Moorland (HMP & YOI)',
  visitStatus: 'SCHEDULED',
  visitStatusDescription: 'Scheduled',
  visitTypeCode: 'VIDEO',
  visitTypeDescription: 'Video',
  visitDate: '2026-01-01',
  startTime: '10:00',
  endTime: '11:00',
  dpsLocationId: 'bef2bbbe-a144-420b-bd23-c10847e61c15',
  locationDescription: 'First Location',
  visitSlotId: 4136,
  prisonerNotes: 'Extra information',
  visitorConcernNotes: '',
  searchTypeCode: 'FULL',
  searchTypeDescription: 'Full search',
  createdTime: '2026-01-19T11:20:48.89632',
  createdBy: 'USERNAME_GEN',
  officialVisitors: [
    {
      officialVisitorId: 1,
      visitorTypeCode: 'CONTACT',
      visitorTypeDescription: 'Contact',
      firstName: 'Peter',
      lastName: 'Malicious',
      contactId: 20085647,
      prisonerContactId: 7332364,
      relationshipTypeCode: 'OFFICIAL',
      relationshipTypeDescription: 'Official',
      relationshipCode: 'SOL',
      relationshipDescription: 'Solicitor',
      leadVisitor: false,
      assistedVisit: true,
      visitorNotes: 'Assistance details',
      createdBy: 'USERNAME_GEN',
      createdTime: '2026-01-19T11:20:48.89633',
      visitorEquipment: {
        description: 'Laptop',
      },
      phoneNumber: '0123456789',
      emailAddress: 'test@test.com',
    },
  ],
  prisonerVisited: {
    prisonerNumber: 'G4793VF',
    prisonCode: 'MDI',
    firstName: 'TIM',
    lastName: 'HARRISON',
    dateOfBirth: '1986-06-27',
    cellLocation: '2-1-007',
    middleNames: 'JETHRONE MASON',
  },
}
