/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/sync/time-slot/{prisonTimeSlotId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Returns the data for a prison time slot by ID
     * @description Requires role: OFFICIAL_VISITS_MIGRATION.
     *           Used to get the details for one prison time slot.
     *
     *
     *     Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     */
    get: operations['syncGetTimeSlotById']
    /**
     * Updates a prison time slot with new or altered details
     * @description Requires role: OFFICIAL_VISITS_MIGRATION.
     *           Used to update a a prison time slot for official visits.
     *
     *
     *     Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     */
    put: operations['syncUpdateTimeSlot']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-dlq/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * OFFICIAL_VISITS_ADMIN
     */
    put: operations['retryDlq']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-all-dlqs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryAllDlqs']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/purge-queue/{queueName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * OFFICIAL_VISITS_ADMIN
     */
    put: operations['purgeQueue']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/time-slot': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Creates a new prison time slot for official visits
     * @description Requires role: OFFICIAL_VISITS_MIGRATION.
     *           Used to create a new prison time slot for official visits.
     *
     *
     *     Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     */
    post: operations['syncCreateTimeSlot']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/official-visit/prison/{prisonCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Endpoint to support the creation of official visits.
     * @description Requires one of the following roles:
     *     * ROLE_OFFICIAL_VISITS_ADMIN
     *     * ROLE_OFFICIAL_VISITS__RW
     */
    post: operations['createOfficialVisit']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/official-visit/prison/{prisonCode}/find-by-criteria': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Endpoint to search for official visit summaries for given search criteria.
     * @description Requires one of the following roles:
     *     * ROLE_OFFICIAL_VISITS_ADMIN
     *     * ROLE_OFFICIAL_VISITS__R
     *     * ROLE_OFFICIAL_VISITS_RW
     */
    post: operations['findByCriteria']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/migrate/visit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Migrate a single official visit and its visitors
     * @description Migrate a visit and all visitors
     *
     *     Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     *     * OFFICIAL_VISITS_ADMIN
     */
    post: operations['migrateVisit']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/migrate/visit-configuration': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Migrate official visits configuration
     * @description Migrate a visit time slot and its associated visit slots, locations and capacity limits
     *
     *     Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     *     * OFFICIAL_VISITS_ADMIN
     */
    post: operations['migrateVisitConfiguration']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/visits-booked/prison/{prisonCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Endpoint to return the official visits booked for a prison - TRIAL ONLY
     * @description Requires one of the following roles:
     *     * ROLE_OFFICIAL_VISITS_ADMIN
     *     * ROLE_OFFICIAL_VISITS__R
     *     * ROLE_OFFICIAL_VISITS__RW
     */
    get: operations['getVisitsBookedForPrison']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reference-data/group/{groupCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Endpoint to return reference data for a provided group key, sorted by display sequence and description
     * @description Requires one of the following roles:
     *     * ROLE_OFFICIAL_VISITS_ADMIN
     *     * ROLE_OFFICIAL_VISITS__R
     *     * ROLE_OFFICIAL_VISITS__RW
     */
    get: operations['getReferenceDataByGroup']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reconcile/prisoner/{prisonerNumber}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Endpoint to return all official visits for a prisoner between the specified  visit dates and  current term
     * @description Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     *     * OFFICIAL_VISITS_ADMIN
     */
    get: operations['getAllOfficialVisitForPrisoner']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reconcile/official-visits/identifiers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Endpoint to return a paged list of all official visit IDs
     * @description Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     *     * OFFICIAL_VISITS_ADMIN
     */
    get: operations['getAllOfficialVisitIds']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reconcile/official-visit/id/{officialVisitId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Endpoint to return one official visit by ID for reconciliation
     * @description Requires one of the following roles:
     *     * OFFICIAL_VISITS_MIGRATION
     *     * OFFICIAL_VISITS_ADMIN
     */
    get: operations['getOfficialVisitById']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/get-dlq-messages/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * OFFICIAL_VISITS_ADMIN
     */
    get: operations['getDlqMessages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisoner/{prisonerNumber}/approved-relationships': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get the approved contacts for a prisoner for official or social visits
     * @description Requires one of the following roles:
     *     * ROLE_OFFICIAL_VISITS_ADMIN
     *     * ROLE_OFFICIAL_VISITS__R
     *     * ROLE_OFFICIAL_VISITS__RW
     */
    get: operations['getApprovedContacts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/official-visit/prison/{prisonCode}/id/{officialVisitId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get an official visit by prison code and ID
     * @description Get the full details of an official visit, its visitors and prisoner details
     *
     *     Requires one of the following roles:
     *     * ROLE_OFFICIAL_VISITS_ADMIN
     *     * ROLE_OFFICIAL_VISITS__R
     *     * ROLE_OFFICIAL_VISITS_RW
     */
    get: operations['getOfficialVisitByPrisonCodeAndId']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/available-slots/{prisonCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Endpoint to return the available slots for official visits for a prison for a given date range.
     * @description Requires one of the following roles:
     *     * ROLE_OFFICIAL_VISITS_ADMIN
     *     * ROLE_OFFICIAL_VISITS__R
     *     * ROLE_OFFICIAL_VISITS__RW
     */
    get: operations['getAvailableSlotsForPrison']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @enum {string} */
    DayType: 'MON' | 'TUE' | 'WED' | 'THU' | 'FRI' | 'SAT' | 'SUN'
    /** @description Request to update a prison time slot for official visits */
    SyncUpdateTimeSlotRequest: {
      /**
       * @description Prison code
       * @example MDI
       */
      prisonCode: string
      /**
       * @description Day code MON-SUN
       * @example MON
       */
      dayCode: components['schemas']['DayType']
      /**
       * @description Start time
       * @example 09:00
       */
      startTime: string
      /**
       * @description End time
       * @example 11:00
       */
      endTime: string
      /**
       * Format: date
       * @description Effective date. The date from which this time slot will be active
       * @example 2026-01-21
       */
      effectiveDate: string
      /**
       * Format: date
       * @description Expiry date. The date from which this time slot will no longer be considered active
       * @example 2027-01-21
       */
      expiryDate?: string
      /**
       * @description User who updated the entry
       * @example admin
       */
      updatedBy: string
      /**
       * Format: date-time
       * @description The timestamp of when this slot was updated
       * @example 2024-01-01T00:00:00Z
       */
      updatedTime: string
    }
    /** @description Sync response for a prison time slot */
    SyncTimeSlot: {
      /**
       * Format: int64
       * @description Time slot ID
       * @example 18767
       */
      prisonTimeSlotId: number
      /**
       * @description Prison code
       * @example MDI
       */
      prisonCode: string
      /**
       * @description Day code MON-SUN
       * @example MON
       */
      dayCode: components['schemas']['DayType']
      /**
       * @description Start time
       * @example 09:00
       */
      startTime: string
      /**
       * @description End time
       * @example 11:00
       */
      endTime: string
      /**
       * Format: date
       * @description Effective date. The date from which this time slot is active
       * @example 2026-01-21
       */
      effectiveDate: string
      /**
       * Format: date
       * @description Expiry date. The date from which this time is no longer be considered active
       * @example 2027-01-21
       */
      expiryDate?: string
      /**
       * @description User who created the entry
       * @example admin
       */
      createdBy: string
      /**
       * Format: date-time
       * @description The timestamp of when this slot was created
       * @example 2024-01-01T00:00:00Z
       */
      createdTime: string
      /**
       * @description User who last updated the entry
       * @example admin
       */
      updatedBy?: string
      /**
       * Format: date-time
       * @description The timestamp of when this slot was last updated
       * @example 2024-01-01T00:00:00Z
       */
      updatedTime?: string
    }
    RetryDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    PurgeQueueResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    /** @description Request to create a new prison time slot for official visits */
    SyncCreateTimeSlotRequest: {
      /**
       * @description Prison code
       * @example MDI
       */
      prisonCode: string
      /**
       * @description Day code MON-SUN
       * @example MON
       */
      dayCode: components['schemas']['DayType']
      /**
       * @description Start time
       * @example 09:00
       */
      startTime: string
      /**
       * @description End time
       * @example 11:00
       */
      endTime: string
      /**
       * Format: date
       * @description Effective date. The date from which this time slot will be active
       * @example 2026-01-21
       */
      effectiveDate: string
      /**
       * Format: date
       * @description Expiry date. The date from which this time slot will no longer be considered active
       * @example 2027-01-21
       */
      expiryDate?: string
      /**
       * @description User who created the entry
       * @example admin
       */
      createdBy: string
      /**
       * Format: date-time
       * @description The timestamp of when this slot was created
       * @example 2024-01-01T00:00:00Z
       */
      createdTime: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description The request with the official visit details */
    CreateOfficialVisitRequest: {
      /** Format: int64 */
      prisonVisitSlotId: number
      /**
       * @description The prisoner number (NOMIS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /**
       * Format: date
       * @description The date the official visit will take place
       * @example 2022-12-23
       */
      visitDate: string
      /**
       * @description The start time of the official visit
       * @example 10:00
       */
      startTime: string
      /**
       * @description The end time of the official visit
       * @example 11:00
       */
      endTime: string
      /**
       * Format: uuid
       * @description The DPS location ID where the official visit is to take place
       * @example aaaa-bbbb-9f9f9f9f-9f9f9f9f
       */
      dpsLocationId: string
      /**
       * @description The visit type code
       * @example IN_PERSON
       */
      visitTypeCode: components['schemas']['VisitType']
      /**
       * @description Notes for staff that will not be shared on movement slips
       * @example Staff notes
       */
      staffNotes?: string
      /**
       * @description Notes for prisoners that may be shared on movement slips
       * @example Prisoner notes
       */
      prisonerNotes?: string
      /**
       * @description Search type code relates to the search that will be done on the prisoner after the visit
       * @example FULL
       */
      searchTypeCode?: components['schemas']['SearchLevelType']
      officialVisitors: components['schemas']['OfficialVisitor'][]
    }
    OfficialVisitor: {
      /**
       * @description The visitor type code (CONTACT, OPV, PRISONER)
       * @example CONTACT
       */
      visitorTypeCode: components['schemas']['VisitorType']
      /**
       * Format: int64
       * @description The contact ID for the visitor
       * @example 123456
       */
      contactId?: number
      /**
       * Format: int64
       * @description The prisoner contact ID for the visitor
       * @example 123456
       */
      prisonerContactId?: number
      /**
       * @description The relationship code
       * @example POM
       */
      relationshipCode: string
      /**
       * @description Set to true if this is the lead visitor
       * @example false
       */
      leadVisitor?: boolean
      /**
       * @description Set to true if this visitor requires an assisted visit
       * @example false
       */
      assistedVisit?: boolean
      /**
       * @description Any required assistance notes to keep about this visitor.  Will be ignored if assisted visit is not true
       * @example Wheelchair access required
       */
      assistedNotes?: string
      /** @description Details of any equipment the visitor will bring to the visit. */
      visitorEquipment?: components['schemas']['VisitorEquipment']
      phoneNumber?: string
      emailAddress?: string
    }
    /** @enum {string} */
    SearchLevelType: 'FULL' | 'PAT' | 'RUB' | 'RUB_A' | 'RUB_B' | 'STR'
    /** @enum {string} */
    VisitType: 'IN_PERSON' | 'TELEPHONE' | 'VIDEO' | 'UNKNOWN'
    VisitorEquipment: {
      /**
       * @description A description of the equipment the visitor will bring
       * @example Laptop
       */
      description: string
    }
    /** @enum {string} */
    VisitorType: 'CONTACT' | 'OPV' | 'PRISONER'
    CreateOfficialVisitResponse: {
      /** Format: int64 */
      officialVisitId: number
    }
    /** @description The request with the official visit summary search details */
    OfficialVisitSummarySearchRequest: {
      /**
       * @description The search term can be a prisoner number, name or partial name.  Must be a minimum of 2 characters or not provided.
       * @example Smith
       */
      searchTerm?: string
      /**
       * Format: date
       * @description The earliest date the official visits will start
       * @example 2022-12-23
       */
      startDate: string
      /**
       * Format: date
       * @description The latest date the official visits will end
       * @example 2022-12-23
       */
      endDate: string
      /**
       * @description The visit types to search for
       * @example IN_PERSON
       * @example VIDEO
       * @example TELEPHONE
       * @example UNKNOWN
       */
      visitTypes?: components['schemas']['VisitType'][]
      /**
       * @description The visit statuses to search for
       * @example SCHEDULED
       * @example COMPLETED
       * @example CANCELLED
       * @example EXPIRED
       */
      visitStatuses?: components['schemas']['VisitStatusType'][]
      /**
       * @description The prisoner numbers to search for
       * @example G9190VP
       * @example G9190VP
       */
      prisonerNumbers?: string[]
      /**
       * @description The location identifiers to search for
       * @example aaaa-bbbb-9f9f9f9f-9f9f9f9f
       */
      locationIds?: string[]
    }
    /** @enum {string} */
    VisitStatusType: 'SCHEDULED' | 'CANCELLED' | 'COMPLETED' | 'EXPIRED'
    OfficialVisitSummarySearchResponse: {
      /**
       * Format: int64
       * @description The official visit id
       * @example 1
       */
      officialVisitId: number
      /**
       * @description The 3 letter code for the prison
       * @example MDI
       */
      prisonCode: string
      /**
       * @description The official visit prison description
       * @example Moorland (HMP & YOI)
       */
      prisonDescription: string
      /**
       * @description The official visit status type
       * @example SCHEDULED
       */
      visitStatus: components['schemas']['VisitStatusType']
      /**
       * @description The official visit status description
       * @example Visit status description
       */
      visitStatusDescription: string
      /**
       * @description The official visit type code
       * @example IN_PERSON
       */
      visitTypeCode: components['schemas']['VisitType']
      /** @description The official visit type description */
      visitTypeDescription: string
      /**
       * Format: date
       * @description The date the official visit takes place
       * @example 2022-12-23
       */
      visitDate: string
      /**
       * @description The start time of the official visit
       * @example 10:00
       */
      startTime: string
      /**
       * @description The end time of the official visit
       * @example 11:00
       */
      endTime: string
      /**
       * Format: uuid
       * @description The DPS location ID where the official visit takes place
       * @example aaaa-bbbb-9f9f9f9f-9f9f9f9f
       */
      dpsLocationId: string
      /**
       * @description The official visit location description
       * @example Legal visits ward
       */
      locationDescription: string
      /**
       * Format: int64
       * @description The prison visit slot identifier for the official visit slot
       * @example 1
       */
      visitSlotId: number
      /**
       * @description Notes for staff that will not be shared on movement slips
       * @example Legal representation details
       */
      staffNotes?: string
      /**
       * @description Notes for prisoners that may be shared on movement slips
       * @example Please arrive 10 minutes early
       */
      prisonerNotes?: string
      visitorConcernNotes?: string
      /**
       * Format: int32
       * @description The number of visitors attending the official visit
       * @example 2
       */
      numberOfVisitors: number
      /**
       * @description The official visit completion type
       * @example VISITOR_CANCELLED
       */
      completionCode?: components['schemas']['VisitCompletionType']
      /** @description The official visit completion description */
      completionDescription?: string
      /**
       * @description The name of the user who created the official visit
       * @example Fred Bloggs
       */
      createdBy: string
      /**
       * Format: date-time
       * @description The date and time the official visit was created
       * @example 2025-12-02 14:45
       */
      createdTime: string
      /**
       * @description The name of the last user who updated the official visit
       * @example Jane Bloggs
       */
      updatedBy?: string
      /**
       * Format: date-time
       * @description The date and time the official visit was last updated
       * @example 22025-12-04 09:50
       */
      updatedTime?: string
      /** @description The details of the prisoner being visited */
      prisoner: components['schemas']['PrisonerVisitedDetails']
    }
    PageMetadata: {
      /** Format: int64 */
      size?: number
      /** Format: int64 */
      number?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int64 */
      totalPages?: number
    }
    PagedModelOfficialVisitSummarySearchResponse: {
      content?: components['schemas']['OfficialVisitSummarySearchResponse'][]
      page?: components['schemas']['PageMetadata']
    }
    PrisonerVisitedDetails: {
      /**
       * @description The official visitor - prisoner number
       * @example 1
       */
      prisonerNumber: string
      /** @description The official visitor Prisoner code */
      prisonCode: string
      /** @description The official visitor - Prisoner first name */
      firstName?: string
      /** @description The official visitor prisoner last name */
      lastName?: string
      /**
       * Format: date
       * @description The official visitor - Prisoner date of birth
       */
      dateOfBirth?: string
      /** @description Prisoner Cell location */
      cellLocation?: string
      /** @description Prisoner middle name */
      middleNames?: string
      /**
       * Format: int64
       * @description Prisoner offender booking id
       */
      offenderBookId?: number
      /** @description Prisoner attendance code */
      attendanceCode?: string
      /** @description Prisoner attendance code description */
      attendanceCodeDescription?: string
    }
    /** @enum {string} */
    VisitCompletionType:
      | 'NORMAL'
      | 'STAFF_CANCELLED'
      | 'VISITOR_CANCELLED'
      | 'VISITOR_DENIED'
      | 'PRISONER_EARLY'
      | 'VISITOR_EARLY'
      | 'PRISONER_REFUSED'
      | 'STAFF_EARLY'
      | 'PRISONER_CANCELLED'
      | 'VISITOR_NO_SHOW'
    /** @enum {string} */
    AttendanceType: 'ATTENDED' | 'ABSENT'
    MigrateVisitRequest: {
      /**
       * Format: int64
       * @description The NOMIS offender visit ID
       * @example 133232
       */
      offenderVisitId: number
      /**
       * Format: int64
       * @description The DPS visit slot ID - this provides the location, start time and end time via configuration data
       * @example 123132
       */
      prisonVisitSlotId: number
      /**
       * @description The prison code where the visit takes place
       * @example PVI
       */
      prisonCode: string
      /**
       * Format: int64
       * @description The offender book ID to echo back. It will be stored in DPS against the visit.
       * @example 74748
       */
      offenderBookId: number
      /**
       * @description The prisoner number (NOMS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /**
       * @description If this visits relates to the current or latest term (booking) in prison true, else false.
       * @example true
       */
      currentTerm: boolean
      /**
       * Format: date
       * @description The date the official visit will take place
       * @example 2022-12-23
       */
      visitDate: string
      /**
       * @description The start time for this official visit
       * @example 09:15
       */
      startTime: string
      /**
       * @description The end time for this official visit
       * @example 10:15
       */
      endTime: string
      /**
       * Format: uuid
       * @description The DPS location where the visit takes place.
       * @example aaaa-bbbb-xxxxxxxx-yyyyyyyy
       */
      dpsLocationId: string
      /**
       * @description The DPS visit status code. The Syscon migration service will map the NOMIS state to a value in this enumerated type.
       * @example SCHEDULED
       */
      visitStatusCode: components['schemas']['VisitStatusType']
      /**
       * @description The DPS visit type code. For migrated NOMIS visits this will default to type UNKNOWN. Other values are IN_PERSON, VIDEO, or TELEPHONE.
       * @example UNKNOWN
       */
      visitTypeCode?: components['schemas']['VisitType']
      /**
       * @description The visit comment text
       * @example This is a comment
       */
      commentText?: string
      /**
       * @description The prisoner search type code. Maps to the same reference code values in both NOMIS and DPS.
       * @example RUB_A
       */
      searchTypeCode?: components['schemas']['SearchLevelType']
      /**
       * @description The DPS visit completion code. Default is NORMAL if not supplied.
       * @example NORMAL
       */
      visitCompletionCode?: components['schemas']['VisitCompletionType']
      /**
       * @description Visit concern text from NOMIS
       * @example I am concerned
       */
      visitorConcernText?: string
      /**
       * @description The staff username who authorised an override for a ban for this visit
       * @example X3243H
       */
      overrideBanStaffUsername?: string
      /**
       * Format: int64
       * @description The visit order number (if present) for the official visit
       * @example 12344
       */
      visitOrderNumber?: number
      /**
       * Format: date-time
       * @description The data and time the record was created
       * @example 2022-10-01T16:45:45
       */
      createDateTime: string
      /**
       * @description The username who created the row
       * @example X999X
       */
      createUsername: string
      /**
       * Format: date-time
       * @description The date and time the record was last amended
       * @example 2022-10-01T16:45:45
       */
      modifyDateTime?: string
      /**
       * @description The username who last modified the row
       * @example X999X
       */
      modifyUsername?: string
      visitors: components['schemas']['MigrateVisitor'][]
    }
    /** @description The details of an official visitor */
    MigrateVisitor: {
      /**
       * Format: int64
       * @description The NOMIS offender visit visitor ID
       * @example 133232
       */
      offenderVisitVisitorId: number
      /**
       * Format: int64
       * @description The NOMIS person ID (same as contactId) for this visitor
       * @example 13989898
       */
      personId: number
      /**
       * @description The first name of the visitor
       * @example Bob
       */
      firstName?: string
      /**
       * @description The last name of the visitor
       * @example Harris
       */
      lastName?: string
      /**
       * Format: date
       * @description The visitors date of birth
       * @example 2011-01-03
       */
      dateOfBirth?: string
      /**
       * @description The relationship type OFFICIAL or SOCIAL. Default is null if not known.
       * @example OFFICIAL
       */
      relationshipTypeCode?: components['schemas']['RelationshipType']
      /**
       * @description The relationship code between visitor and prisoner, from NOMIS reference data. A null value will indicate no relationship.
       * @example POL
       */
      relationshipToPrisoner?: string
      /**
       * @description Set to true if this person is the lead visitor. Defaults to false if not supplied.
       * @example true
       */
      groupLeaderFlag?: boolean
      /**
       * @description Set to true if this person requires assistance at the visit. Defaults to false if not supplied.
       * @example true
       */
      assistedVisitFlag?: boolean
      /**
       * @description The visitor comment text from NOMIS
       * @example Some comments
       */
      commentText?: string
      /**
       * @description The visitor attendance code (ATTENDED or ABSENT). A null indicates no attendance was added.
       * @example ATTENDED
       */
      attendanceCode?: components['schemas']['AttendanceType']
      /**
       * Format: date-time
       * @description The data and time the record was created
       * @example 2022-10-01T16:45:45
       */
      createDateTime: string
      /**
       * @description The username who created the row
       * @example X999X
       */
      createUsername: string
      /**
       * Format: date-time
       * @description The date and time the record was last amended
       * @example 2022-10-01T16:45:45
       */
      modifyDateTime?: string
      /**
       * @description The username who last modified the row
       * @example X999X
       */
      modifyUsername?: string
    }
    /** @enum {string} */
    RelationshipType: 'OFFICIAL' | 'SOCIAL'
    IdPair: {
      /**
       * @description The category of information returned
       * @example PRISON_VISIT_SLOT
       * @enum {string}
       */
      elementType: 'PRISON_VISIT_SLOT' | 'OFFICIAL_VISIT' | 'OFFICIAL_VISITOR' | 'PRISONER_VISITED'
      /**
       * Format: int64
       * @description The unique ID for this data item provided in the request
       * @example 123435
       */
      nomisId: number
      /**
       * Format: int64
       * @description The unique ID created in the DPS official visits service
       * @example 1234
       */
      dpsId: number
    }
    /** @description The migration response for an official visit and the visitors attending */
    MigrateVisitResponse: {
      /** @description The pair of IDs for this visit */
      visit: components['schemas']['IdPair']
      /** @description The list of ID pairs for each visitor on this visit */
      visitors: components['schemas']['IdPair'][]
      /** @description The pair of IDs for the prisoner on this visit. NOMS ID is used as the NOMIS ID, as it has no other ID */
      prisoner: components['schemas']['IdPair']
    }
    /** @description Request to migrate a day and time slot for a prison and its associated visit slots from NOMIS */
    MigrateVisitConfigRequest: {
      /**
       * @description The 3-letter agy_loc_id from NOMIS where this visit time slot exists
       * @example MDI
       */
      prisonCode: string
      /**
       * @description The 3-letter day of the week code where this slot falls in this prison.
       * @example TUE
       */
      dayCode: string
      /**
       * Format: int32
       * @description The time slot sequence in NOMIS. This is used to build a response object for cross-reference
       * @example 1
       */
      timeSlotSeq: number
      /**
       * @description The start time for this visit time slot
       * @example 13:30
       */
      startTime: string
      /**
       * @description The end time for this visit time slot
       * @example 14:30
       */
      endTime: string
      /**
       * Format: date
       * @description The date from which this row will be effective
       * @example 1980-01-01
       */
      effectiveDate: string
      /**
       * Format: date
       * @description The date from which this row will no longer be effective
       * @example 1980-01-01
       */
      expiryDate?: string
      /** @description The list of visit slots which are linked to this time slot */
      visitSlots: components['schemas']['MigrateVisitSlot'][]
      /**
       * Format: date-time
       * @description The data and time the record was created
       * @example 2022-10-01T16:45:45
       */
      createDateTime?: string
      /**
       * @description The username who created the record
       * @example X999X
       */
      createUsername?: string
      /**
       * Format: date-time
       * @description The date and time the record was last amended
       * @example 2022-10-01T16:45:45
       */
      modifyDateTime?: string
      /**
       * @description The username who last modified the record
       * @example X999X
       */
      modifyUsername?: string
    }
    MigrateVisitSlot: {
      /**
       * Format: int64
       * @description Unique ID for this visit slot in NOMIS. For building a response to cross-reference with a DPS visit slot.
       * @example 1
       */
      agencyVisitSlotId: number
      /**
       * Format: int64
       * @description The internal location ID from NOMIS. Information only
       * @example 1090909
       */
      internalLocationId?: number
      /**
       * @description The location key from NOMIS. Information only
       * @example MDI-OFFICIAL_VISITS
       */
      locationKey?: string
      /**
       * Format: uuid
       * @description The DPS location ID (mapped from the NOMIS internal location ID)
       * @example 9485cf4a-750b-4d74-b594-59bacbcda247
       */
      dpsLocationId: string
      /**
       * Format: int32
       * @description The maximum number of groups that can be booked into this visit slot. Effectively, the max visits limit for the slot.
       * @example 8
       */
      maxGroups?: number
      /**
       * Format: int32
       * @description The maximum number of adults who can be booked into this visits slot.
       * @example 22
       */
      maxAdults?: number
      /**
       * Format: int32
       * @description The maximum number of video sessions that can be booked into this visits slot.
       * @example 8
       */
      maxVideoSessions?: number
      /**
       * Format: date-time
       * @description The data and time the record was created
       * @example 2022-10-01T16:45:45
       */
      createDateTime?: string
      /**
       * @description The username who created the record
       * @example X999X
       */
      createUsername?: string
      /**
       * Format: date-time
       * @description The date and time the record was last amended
       * @example 2022-10-01T16:45:45
       */
      modifyDateTime?: string
      /**
       * @description The username who last modified the record
       * @example X999X
       */
      modifyUsername?: string
    }
    /** @description The migration response for an official visit time slot and its visit slots */
    MigrateVisitConfigResponse: {
      /**
       * @description The 3-letter agy_loc_id from NOMIS where this time slot exists
       * @example MDI
       */
      prisonCode: string
      /**
       * @description The 3-letter day of the week code where this slot exists in this prison.
       * @example TUE
       */
      dayCode: string
      /**
       * Format: int32
       * @description The time slot sequence from NOMIS
       * @example 1
       */
      timeSlotSeq: number
      /**
       * Format: int64
       * @description The ID created in DPS for this prison time slot
       * @example 123456
       */
      dpsTimeSlotId: number
      /** @description List of NOMIS and DPS IDs for the visit slots created */
      visitSlots: components['schemas']['IdPair'][]
    }
    VisitBookedEntity: {
      /** Format: int64 */
      officialVisitId: number
      prisonCode: string
      dayCode: string
      dayDescription: string
      /** Format: int64 */
      prisonVisitSlotId: number
      /** Format: int64 */
      prisonTimeSlotId: number
      /** Format: date */
      visitDate: string
      startTime: string
      endTime: string
      visitStatusCode?: string
      visitTypeCode: string
      prisonerNumber: string
      /** Format: int64 */
      contactId?: number
      visitorTypeCode?: string
      relationshipTypeCode?: string
      relationshipCode?: string
      firstName?: string
      lastName?: string
      /** Format: uuid */
      dpsLocationId: string
    }
    /** @enum {string} */
    ReferenceDataGroup:
      | 'ATTENDANCE'
      | 'DAY'
      | 'RELATIONSHIP_TYPE'
      | 'SEARCH_LEVEL'
      | 'TEST_TYPE'
      | 'VIS_COMPLETION'
      | 'VIS_STATUS'
      | 'VIS_TYPE'
      | 'VISITOR_TYPE'
    /** @description Describes the details of a reference code */
    ReferenceDataItem: {
      /**
       * Format: int64
       * @description An internally-generated unique identifier for this reference code.
       * @example 12345
       */
      referenceDataId: number
      /**
       * @description The group name for related reference codes.
       * @example VIS_STATUS
       */
      groupCode: components['schemas']['ReferenceDataGroup']
      /**
       * @description The code for this reference data
       * @example SCHEDULED
       */
      code: string
      /**
       * @description A fuller description of the reference code
       * @example Scheduled
       */
      description: string
      /**
       * Format: int32
       * @description The default order configured for the reference code, lowest number first.
       * @example 5
       */
      displaySequence: number
      /**
       * @description Whether the reference code is still in use. Old reference codes are maintained for compatability with legacy data.
       * @example true
       */
      enabled: boolean
    }
    SyncOfficialVisit: {
      /**
       * Format: int64
       * @description The internal official visit ID
       * @example 1
       */
      officialVisitId: number
      /**
       * Format: date
       * @description The visit date
       * @example 2020-01-02
       */
      visitDate: string
      /**
       * @description The visit start time
       * @example 09:15
       */
      startTime: string
      /**
       * @description The visit end time
       * @example 10:15
       */
      endTime: string
      /**
       * Format: int64
       * @description The visit slot ID
       * @example 12345
       */
      prisonVisitSlotId: number
      /**
       * Format: uuid
       * @description The DPS location ID where the visit is taking place
       * @example aaa-ddd-bbb-123455632323
       */
      dpsLocationId: string
      /**
       * @description The prison establishment code
       * @example MDI
       */
      prisonCode: string
      /**
       * @description The prisoner number
       * @example A1111AA
       */
      prisonerNumber: string
      /**
       * @description The visit status code
       * @example SCHEDULED
       */
      statusCode: components['schemas']['VisitStatusType']
      /**
       * @description The visit completion code
       * @example NORMAL
       */
      completionCode?: components['schemas']['VisitCompletionType']
      /**
       * Format: int64
       * @description The offender booking ID in NOMIS
       * @example 12345
       */
      offenderBookId?: number
      /**
       * Format: int64
       * @description The offender visit ID in NOMIS (only present for migrated bookings)
       * @example 12345
       */
      offenderVisitId?: number
      /** @description The offender visitor details */
      visitors: components['schemas']['SyncOfficialVisitor'][]
    }
    SyncOfficialVisitor: {
      /**
       * Format: int64
       * @description The internal official visitor ID
       * @example 1
       */
      officialVisitorId: number
      /**
       * Format: int64
       * @description The contact ID of the person visiting
       * @example 123
       */
      contactId?: number
      /**
       * @description The visitor first Name
       * @example John
       */
      firstName?: string
      /**
       * @description The visitor last Name
       * @example Smith
       */
      lastName?: string
      /**
       * @description The relationship type for this visitor (OFFICIAL or SOCIAL)
       * @example OFFICIAL
       */
      relationshipType?: components['schemas']['RelationshipType']
      /**
       * @description The visitor relationship code
       * @example POM
       */
      relationshipCode?: string
      /**
       * @description The visitor attendance code, either ABSENT, ATTENDED or null if not recorded.
       * @example ABSENT
       */
      attendanceCode?: components['schemas']['AttendanceType']
    }
    PagedModelSyncOfficialVisitId: {
      content?: components['schemas']['SyncOfficialVisitId'][]
      page?: components['schemas']['PageMetadata']
    }
    /** @description Response object for sync reconciliation */
    SyncOfficialVisitId: {
      /**
       * Format: int64
       * @description The ID for an Official visits
       * @example 111111
       */
      officialVisitId: number
    }
    DlqMessage: {
      body: {
        [key: string]: unknown
      }
      messageId: string
    }
    GetDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      /** Format: int32 */
      messagesReturnedCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    ApprovedContact: {
      /**
       * Format: int64
       * @description The prisoner contact number
       * @example 1
       */
      prisonerContactId: number
      /**
       * Format: int64
       * @description The unique identifier for the prisoner contact
       * @example 1
       */
      contactId: number
      /** @description Prisoner number (NOMS ID) */
      prisonerNumber: string
      /** @description The last name of the contact */
      lastName: string
      /** @description The first name of the contact */
      firstName: string
      /** @description Coded value indicating either a social or official contact */
      relationshipTypeCode: string
      /** @description Relationship type Description */
      relationshipTypeDescription: string
      /** @description The relationship to the prisoner. A code from SOCIAL_RELATIONSHIP or OFFICIAL_RELATIONSHIP reference data groups depending on the relationship type. */
      relationshipToPrisonerCode: string
      /** @description Relationship type Description */
      relationshipToPrisonerDescription: string
      /** @description Indicates whether the contact is an approved visitor */
      isApprovedVisitor: boolean
      /** @description Is this contact the prisoner's next of kin? */
      isNextOfKin: boolean
      /** @description Is this contact the prisoner's emergency contact? */
      isEmergencyContact: boolean
      /** @description Is this prisoner's contact relationship active? */
      isRelationshipActive: boolean
      /** @description Is this relationship active for the current booking? */
      currentTerm: boolean
      /** @description Whether the contact is a staff member */
      isStaff: boolean
      /** @description Restriction Summary */
      restrictionSummary: components['schemas']['RestrictionsSummary']
      /** @description The title code for the contact */
      titleCode?: string
      /** @description The description of the title code, if present */
      titleDescription?: string
      /** @description The middle names of the contact, if any */
      middleNames?: string
      /**
       * Format: date
       * @description The date of birth of the contact
       */
      dateOfBirth?: string
      /**
       * Format: date
       * @description The date the contact deceased, if known
       */
      deceasedDate?: string
      /** @description Flat number in the address, if any */
      flat?: string
      /** @description Property name or number */
      property?: string
      /** @description Street Name */
      street?: string
      /** @description Area or locality, if any */
      area?: string
      /** @description City code */
      cityCode?: string
      /** @description The description of city code */
      cityDescription?: string
      /** @description Country code */
      countyCode?: string
      /** @description The description of county code */
      countyDescription?: string
      /** @description Postal code */
      postcode?: string
      /** @description Country Code */
      countryCode?: string
      /** @description Flag to indicate whether this address indicates no fixed address */
      countryDescription?: string
      /** @description Flag to indicate whether this address indicates no fixed address */
      noFixedAddress?: boolean
      /** @description If true this address should be considered as the primary residential address */
      primaryAddress?: boolean
      /** @description If true this address should be considered for sending mail to */
      mailAddress?: boolean
      /** @description Type of the latest phone number */
      phoneType?: string
      /** @description Description of the type of the latest phone number */
      phoneTypeDescription?: string
      /** @description The latest phone number, if there are any */
      phoneNumber?: string
      /** @description The extension number of the latest phone number */
      extNumber?: string
    }
    RestrictionTypeDetails: {
      restrictionType: string
      restrictionTypeDescription: string
    }
    RestrictionsSummary: {
      active: components['schemas']['RestrictionTypeDetails'][]
      /** Format: int32 */
      totalActive: number
      /** Format: int32 */
      totalExpired: number
    }
    OfficialVisitDetails: {
      /**
       * Format: int64
       * @description The official visit id
       * @example 1
       */
      officialVisitId: number
      /**
       * @description The prison code
       * @example MDI
       */
      prisonCode: string
      /**
       * @description The official visit prison description
       * @example Moorland (HMP & YOI)
       */
      prisonDescription?: string
      /** @description The Official visit status type */
      visitStatus: components['schemas']['VisitStatusType']
      /**
       * @description The Official visit status description
       * @example Visit Status
       */
      visitStatusDescription?: string
      /**
       * @description The Official visit visit type
       * @example AP
       */
      visitTypeCode: components['schemas']['VisitType']
      /** @description The Official visit type description */
      visitTypeDescription: string
      /**
       * Format: date
       * @description The Official visit date
       */
      visitDate: string
      /** @description The Official visit start time */
      startTime: string
      /** @description The Official visit end time */
      endTime: string
      /**
       * Format: uuid
       * @description The Official visit Location Id
       */
      dpsLocationId: string
      /** @description The Official visit location description */
      locationDescription?: string
      /**
       * Format: int64
       * @description The Official visit - visitor slot slot identifier for the official visit takes place
       */
      visitSlotId?: number
      /** @description The Official visit - staff notes */
      staffNotes?: string
      /** @description The Official visit - prisoner notes */
      prisonerNotes?: string
      /** @description The Official visit - visitor concern notes */
      visitorConcernNotes?: string
      /** @description The Official visit completion type */
      completionCode?: components['schemas']['VisitCompletionType']
      /** @description The Official visit creation description */
      completionDescription?: string
      /** @description The Official visit Search Level type */
      searchTypeCode?: components['schemas']['SearchLevelType']
      /** @description The Official visit search type */
      searchTypeDescription?: string
      /**
       * Format: date-time
       * @description The Official visit creation time
       */
      createdTime: string
      /** @description The Official visit created by User */
      createdBy: string
      /**
       * Format: date-time
       * @description The Official visit updated date time
       */
      updatedTime?: string
      /** @description The Official visit updated by user */
      updatedBy?: string
      /** @description The Official visit updated by user */
      officialVisitors?: components['schemas']['OfficialVisitorDetails'][]
      /** @description The Prisoner Information */
      prisonerVisited?: components['schemas']['PrisonerVisitedDetails']
    }
    OfficialVisitorDetails: {
      /** @description The Official visitor Visit Type code */
      visitorTypeCode: components['schemas']['VisitorType']
      /** @description The Official visitor TypeDescription */
      visitorTypeDescription?: string
      /** @description The Official visitor first name */
      firstName?: string
      /** @description The Official visitor last name */
      lastName?: string
      /**
       * Format: int64
       * @description The Official visitor contact id
       */
      contactId?: number
      /**
       * Format: int64
       * @description The prisoner contact id
       */
      prisonerContactId?: number
      /** @description The Official visitor relationship type code */
      relationshipTypeCode?: components['schemas']['RelationshipType']
      /** @description The Official visitor relationship Type Description */
      relationshipTypeDescription?: string
      /** @description The Official visitor relationship code */
      relationshipCode?: string
      /** @description The Official visitor relationship description */
      relationshipDescription?: string
      /** @description The Official visitor - is lead visitor */
      leadVisitor: boolean
      /** @description The Official visitor - is assisted visit */
      assistedVisit: boolean
      /** @description The Official visitor visitor notes */
      visitorNotes?: string
      /** @description The Official visitor attendance type */
      attendanceCode?: components['schemas']['AttendanceType']
      /** @description The Official visitor attendance description */
      attendanceDescription?: string
      /** @description The Official visitor created by user */
      createdBy: string
      /**
       * Format: date-time
       * @description The Official visitor created date time
       */
      createdTime: string
      /** @description The Official visitor updated by user */
      updatedBy?: string
      /**
       * Format: date-time
       * @description The Official visitor updated date time
       */
      updatedTime?: string
      /**
       * Format: int64
       * @description The Official visitor offender visit visitor id
       */
      offenderVisitVisitorId?: number
      /** @description Equipment the visitor may bring */
      visitorEquipment?: components['schemas']['VisitorEquipment']
      /**
       * @description Notes on whether the visitor requires any assistance
       * @example Wheelchair access required
       */
      assistanceNotes?: string
      phoneNumber?: string
      emailAddress?: string
    }
    AvailableSlot: {
      /**
       * Format: int64
       * @description The prison visit slot identifier for the official visit slot
       * @example 1
       */
      visitSlotId: number
      /**
       * Format: int64
       * @description The prison time slot identifier for the official visit slot
       * @example 1
       */
      timeSlotId: number
      /**
       * @description The prison code where the visit takes place
       * @example PVI
       */
      prisonCode: string
      /**
       * @description The 3-letter day of the week code where this slot falls in this prison.
       * @example TUE
       */
      dayCode: string
      /**
       * @description The day of the week code where this slot falls in this prison.
       * @example Tuesday
       */
      dayDescription: string
      /**
       * Format: date
       * @description The date for the official visit slot
       */
      visitDate: string
      /** @description The start time for the official visit slot */
      startTime: string
      /** @description The end time for the official visit slot */
      endTime: string
      /**
       * Format: uuid
       * @description The DPS location where the official visit takes place for the slot
       * @example aaaa-bbbb-xxxxxxxx-yyyyyyyy
       */
      dpsLocationId: string
      /**
       * Format: int32
       * @description The available video sessions for official visit slot
       */
      availableVideoSessions: number
      /**
       * Format: int32
       * @description The available adults for official visit slot
       */
      availableAdults: number
      /**
       * Format: int32
       * @description The available groups for official visit slot
       */
      availableGroups: number
      /**
       * @description The description of the location where this slot exists
       * @example Legal visits room 8
       */
      locationDescription?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  syncGetTimeSlotById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The internal ID for a prison time slot */
        prisonTimeSlotId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The prison time slot matching the ID provided in the request */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncTimeSlot']
        }
      }
      /** @description No prison time slot with this ID was found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncTimeSlot']
        }
      }
    }
  }
  syncUpdateTimeSlot: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The internal ID for the prison time slot */
        prisonTimeSlotId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncUpdateTimeSlotRequest']
      }
    }
    responses: {
      /** @description Successfully updated a prison time slot */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncTimeSlot']
        }
      }
      /** @description Invalid data supplied in the request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncTimeSlot']
        }
      }
      /** @description The prison time slot ID was not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncTimeSlot']
        }
      }
    }
  }
  retryDlq: {
    parameters: {
      query?: never
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult']
        }
      }
    }
  }
  retryAllDlqs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult'][]
        }
      }
    }
  }
  purgeQueue: {
    parameters: {
      query?: never
      header?: never
      path: {
        queueName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PurgeQueueResult']
        }
      }
    }
  }
  syncCreateTimeSlot: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncCreateTimeSlotRequest']
      }
    }
    responses: {
      /** @description Successfully created a prison time slot for official visits */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncTimeSlot']
        }
      }
      /** @description The request was invalid or had missing fields */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  createOfficialVisit: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The prison code
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOfficialVisitRequest']
      }
    }
    responses: {
      /** @description The response containing the details of the created official visit */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateOfficialVisitResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findByCriteria: {
    parameters: {
      query?: {
        /** @description Zero-based page index (0..N) */
        page?: number
        /** @description The size of the page to be returned */
        size?: number
      }
      header?: never
      path: {
        /**
         * @description The prison code
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OfficialVisitSummarySearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PagedModelOfficialVisitSummarySearchResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  migrateVisit: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MigrateVisitRequest']
      }
    }
    responses: {
      /** @description The visit and visitor ID mappings between NOMIS and DPS */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MigrateVisitResponse']
        }
      }
      /** @description The request failed validation with invalid or missing data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  migrateVisitConfiguration: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MigrateVisitConfigRequest']
      }
    }
    responses: {
      /** @description The time slot and associated visit slots was migrated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MigrateVisitConfigResponse']
        }
      }
      /** @description The request failed validation with invalid or missing data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getVisitsBookedForPrison: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The prison code
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of visits booked at the prison */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VisitBookedEntity'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getReferenceDataByGroup: {
    parameters: {
      query?: {
        /** @description Whether to only return active codes or not, defaults to true */
        activeOnly?: boolean
      }
      header?: never
      path: {
        /**
         * @description The group code of the reference codes to load
         * @example VIS_STATUS
         */
        groupCode: components['schemas']['ReferenceDataGroup']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of reference data codes/values */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferenceDataItem'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getAllOfficialVisitForPrisoner: {
    parameters: {
      query?: {
        /** @description Is current term only? */
        currentTermOnly?: boolean
        /** @description The from date in ISO format (YYYY-MM-DD). */
        fromDate?: string
        /** @description The to date in ISO format (YYYY-MM-DD). */
        toDate?: string
      }
      header?: never
      path: {
        /** @description The prisoner Number */
        prisonerNumber: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of all Official visit details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncOfficialVisit'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getAllOfficialVisitIds: {
    parameters: {
      query?: {
        currentTermOnly?: boolean
        /** @description Zero-based page index (0..N) */
        page?: number
        /** @description The size of the page to be returned */
        size?: number
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[]
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A paginated list of all official visit IDs */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PagedModelSyncOfficialVisitId']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getOfficialVisitById: {
    parameters: {
      query?: never
      header?: never
      path: {
        officialVisitId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Official visit details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncOfficialVisit']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getDlqMessages: {
    parameters: {
      query?: {
        maxMessages?: number
      }
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetDlqResult']
        }
      }
    }
  }
  getApprovedContacts: {
    parameters: {
      query?: {
        /** @description The relationship type should be S for social or O for official */
        relationshipType?: string
      }
      header?: never
      path: {
        prisonerNumber: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of approved contacts of the prisoner */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovedContact'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description The prisoner was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getOfficialVisitByPrisonCodeAndId: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The prison code
         * @example MIC
         */
        prisonCode: string
        /**
         * @description The official visit ID
         * @example 123456
         */
        officialVisitId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Official visit found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OfficialVisitDetails']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description No official visit found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getAvailableSlotsForPrison: {
    parameters: {
      query: {
        /** @description The from date in ISO format (YYYY-MM-DD). */
        fromDate: string
        /** @description The to date in ISO format (YYYY-MM-DD). */
        toDate: string
        /** @description Boolean flag. A value of 'true' will only return video reservable slots. */
        videoOnly?: boolean
      }
      header?: never
      path: {
        /**
         * @description The prison code
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of available slots at the prison */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AvailableSlot'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
