import { Response } from 'express'
import OfficialVisitsApiClient from '../data/officialVisitsApiClient'
import { HmppsUser } from '../interfaces/hmppsUser'
import {
  CreateOfficialVisitRequest,
  CreateOfficialVisitResponse,
  FindByCriteria,
  OfficialVisit,
  OfficialVisitor,
  SearchLevelType,
  VisitorEquipment,
  VisitorType,
} from '../@types/officialVisitsApi/types'
import { OfficialVisitJourney } from '../routes/journeys/manage/visit/journey'
import logger from '../../logger'
import { components } from '../@types/officialVisitsApi'

export default class OfficialVisitsService {
  constructor(private readonly officialVisitsApiClient: OfficialVisitsApiClient) {}

  public async getOfficialVisitById(prisonCode: string, visitId: number, user: HmppsUser): Promise<OfficialVisit> {
    return this.officialVisitsApiClient.getOfficialVisitById(prisonCode, visitId, user)
  }

  public visitIsAmendable(date: Date, startTime: Date, visitStatusCode: string) {
    // TODO: Populate the rules here
    logger.info(`Just using vars ${date}, ${startTime}, ${visitStatusCode}`)
    return true
  }

  public async createVisit(sessionVisit: OfficialVisitJourney, user: HmppsUser): Promise<CreateOfficialVisitResponse> {
    // Populate the create visit request from the session object
    const request = {
      prisonVisitSlotId: sessionVisit.selectedTimeSlot.visitSlotId,
      prisonCode: sessionVisit.prisonCode,
      prisonerNumber: sessionVisit.prisoner.prisonerNumber,
      visitDate: sessionVisit.selectedTimeSlot.visitDate,
      startTime: sessionVisit.selectedTimeSlot.startTime,
      endTime: sessionVisit.selectedTimeSlot.endTime,
      dpsLocationId: sessionVisit.selectedTimeSlot.dpsLocationId,
      visitTypeCode: sessionVisit.visitType,
      staffNotes: sessionVisit.staffNotes, // Not supplied by UI journey yet
      prisonerNotes: sessionVisit.prisonerNotes,
      searchTypeCode: 'FULL' as SearchLevelType, // Not supplied by UI journey yet
      officialVisitors: [...sessionVisit.officialVisitors, ...sessionVisit.socialVisitors].map(o => ({
        visitorTypeCode: 'CONTACT' as VisitorType,
        contactId: o.contactId,
        prisonerContactId: o.prisonerContactId,
        relationshipCode: o.relationshipToPrisonerCode,
        leadVisitor: o.leadVisitor,
        assistedVisit: o.assistedVisit,
        assistedNotes: o.assistanceNotes,
        visitorEquipment: {
          description: o.assistanceNotes,
        } as VisitorEquipment,
      })) as OfficialVisitor[],
    } as CreateOfficialVisitRequest

    logger.info(`Create visit request ${JSON.stringify(request, null, 2)}`)

    return this.officialVisitsApiClient.createOfficialVisit(sessionVisit.prisonCode, request, user)
  }

  public async amendVisit(sessionVisit: OfficialVisitJourney, user: HmppsUser) {
    logger.info(`Just using vars ${JSON.stringify(sessionVisit)}, ${JSON.stringify(user)}`)
    // TODO: Map the journey to a VisitAmendRequest, call the service amend, and return the amended visit
  }

  public async getReferenceData(res: Response, code: components['schemas']['ReferenceDataGroup']) {
    return this.officialVisitsApiClient.getReferenceData(code, res.locals.user)
  }

  public async getActiveRestrictions(res: Response, prisonId: string, prisonerNumber: string) {
    return this.officialVisitsApiClient.getActiveRestrictions(prisonId, prisonerNumber, res.locals.user)
  }

  public async getApprovedOfficialContacts(prisonId: string, prisonerNumber: string, user: HmppsUser) {
    return this.officialVisitsApiClient.getApprovedOfficialContacts(prisonId, prisonerNumber, user)
  }

  public async getApprovedSocialContacts(prisonId: string, prisonerNumber: string, user: HmppsUser) {
    return this.officialVisitsApiClient.getApprovedSocialContacts(prisonId, prisonerNumber, user)
  }

  public async getAvailableSlots(res: Response, prisonId: string, startDate: string, endDate: string) {
    return this.officialVisitsApiClient.getAvailableTimeSlots(prisonId, startDate, endDate, res.locals.user)
  }

  public async getSchedule(res: Response, prisonId: string, date: string) {
    return this.officialVisitsApiClient.getSchedule(prisonId, date, res.locals.user)
  }

  public async getVisits(prisonId: string, criteria: FindByCriteria, page: number, size: number, user: HmppsUser) {
    logger.info(`Get visits for prison ${prisonId} with criteria ${JSON.stringify(criteria)}`)
    // const startDate = new Date(criteria.startDate)
    // const endDate = new Date(criteria.endDate)

    // console.log(`Start date ${startDate}, end date ${endDate}`)

    // const mockContents = mockData.filter(o => {
    //   if (criteria.prisonerNumbers?.length && !criteria.prisonerNumbers.includes(o.prisoner.prisonerNumber)) {
    //     return false
    //   }

    //   if (criteria.visitStatuses?.length && !(criteria.visitStatuses as string[]).includes(o.visitStatus)) {
    //     return false
    //   }

    //   if (criteria.visitTypes?.length && !(criteria.visitTypes as string[]).includes(o.visitTypeCode)) {
    //     return false
    //   }

    //   if (criteria.startDate && new Date(o.visitDate) < new Date(criteria.startDate)) {
    //     return false
    //   }

    //   if (criteria.endDate && new Date(o.visitDate) > new Date(criteria.endDate)) {
    //     return false
    //   }

    //   return true
    // })
    // return {
    //   content: mockContents.slice(page * size, (page + 1) * size),
    //   page: {
    //     totalElements: mockContents.length,
    //     totalPages: Math.ceil(mockContents.length / size),
    //     number: page,
    //     size,
    //   },
    // }

    return this.officialVisitsApiClient.getVisits(prisonId, criteria, page, size, user)
  }
}

const mockData = [
  {
    officialVisitId: 294,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '0295322751',
      prisonCode: 'string',
      firstName: 'Jaylani',
      lastName: 'Etheridge',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 378,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 6,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '0248904765',
      prisonCode: 'string',
      firstName: 'Loralie',
      lastName: 'Demars',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 609,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 1,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '6227175801',
      prisonCode: 'string',
      firstName: 'Lionel',
      lastName: 'Muniz',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 983,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 9,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '7354248365',
      prisonCode: 'string',
      firstName: 'Ilias',
      lastName: 'Elswick',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 615,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 8,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '0299496988',
      prisonCode: 'string',
      firstName: 'Helen',
      lastName: 'Duffy',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 451,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 8,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '9382708775',
      prisonCode: 'string',
      firstName: 'Kamber',
      lastName: 'Almendarez',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 578,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 7,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '6360703106',
      prisonCode: 'string',
      firstName: 'Adora',
      lastName: 'Ebersole',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 548,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '5163773592',
      prisonCode: 'string',
      firstName: 'Issa',
      lastName: 'Vaca',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 127,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 9,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '0925117687',
      prisonCode: 'string',
      firstName: 'Zymere',
      lastName: 'Bainbridge',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 952,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 2,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '8963357808',
      prisonCode: 'string',
      firstName: 'Amariyah',
      lastName: 'Lomas',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 618,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 9,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '6921277231',
      prisonCode: 'string',
      firstName: 'Gian',
      lastName: 'Oglesby',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 33,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '1994780998',
      prisonCode: 'string',
      firstName: 'Joana',
      lastName: 'Nakamura',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 177,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 8,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '5621126412',
      prisonCode: 'string',
      firstName: 'Holley',
      lastName: 'Oberg',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 722,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 9,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '8524301991',
      prisonCode: 'string',
      firstName: 'Chyna',
      lastName: 'Hartmann',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 185,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 8,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '9398408995',
      prisonCode: 'string',
      firstName: 'Lark',
      lastName: 'Botelho',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 479,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '8463017976',
      prisonCode: 'string',
      firstName: 'Malique',
      lastName: 'Lovelady',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 217,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '5612091441',
      prisonCode: 'string',
      firstName: 'Anabela',
      lastName: 'Morfin',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 981,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 1,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '1130855772',
      prisonCode: 'string',
      firstName: 'Nazareth',
      lastName: 'Leverett',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 207,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 9,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '7763417064',
      prisonCode: 'string',
      firstName: 'Izabella',
      lastName: 'Salinas',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 75,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '5779015433',
      prisonCode: 'string',
      firstName: 'Mikaylah',
      lastName: 'Deas',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 658,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 1,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '3670251587',
      prisonCode: 'string',
      firstName: 'Yara',
      lastName: 'Call',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 289,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 4,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '1795766248',
      prisonCode: 'string',
      firstName: 'Miri',
      lastName: 'Argo',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 574,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '2053119105',
      prisonCode: 'string',
      firstName: 'Monserrath',
      lastName: 'Liao',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 557,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 8,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '5697615335',
      prisonCode: 'string',
      firstName: 'Zori',
      lastName: 'Ledet',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 101,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '9913868692',
      prisonCode: 'string',
      firstName: 'Dartagnan',
      lastName: 'Morano',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 851,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 1,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '2349213837',
      prisonCode: 'string',
      firstName: 'Zacarias',
      lastName: 'Ignacio',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 487,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '3273912699',
      prisonCode: 'string',
      firstName: 'Aleyza',
      lastName: 'Lampe',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 533,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '0344551219',
      prisonCode: 'string',
      firstName: 'Aerilyn',
      lastName: 'Wightman',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 514,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 0,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '1477524711',
      prisonCode: 'string',
      firstName: 'Denise',
      lastName: 'Cope',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 946,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 7,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '9994447402',
      prisonCode: 'string',
      firstName: 'Canon',
      lastName: 'Heinrich',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 354,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 9,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '3150145660',
      prisonCode: 'string',
      firstName: 'Shahd',
      lastName: 'Schoenfeld',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 331,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '6355963763',
      prisonCode: 'string',
      firstName: 'Loyal',
      lastName: 'Purser',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 573,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '9591038678',
      prisonCode: 'string',
      firstName: 'Victory',
      lastName: 'Wilmoth',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 94,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 7,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '0212391111',
      prisonCode: 'string',
      firstName: 'Khadijah',
      lastName: 'Wadsworth',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 504,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '3417794632',
      prisonCode: 'string',
      firstName: 'Taylah',
      lastName: 'Miele',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 773,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '1473491804',
      prisonCode: 'string',
      firstName: 'Jacion',
      lastName: 'Monday',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 880,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '8388842854',
      prisonCode: 'string',
      firstName: 'Dhriti',
      lastName: 'Maloy',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 875,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 0,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '1899354083',
      prisonCode: 'string',
      firstName: 'Cameron',
      lastName: 'Costello',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 629,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 4,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '7426652162',
      prisonCode: 'string',
      firstName: 'Mahnoor',
      lastName: 'Stoller',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 798,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 0,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '6282658233',
      prisonCode: 'string',
      firstName: 'Deetya',
      lastName: 'Driskill',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 679,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 6,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '7235235599',
      prisonCode: 'string',
      firstName: 'Delphine',
      lastName: 'Hatley',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 207,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'VIDEO',
    visitTypeDescription: 'Video',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 0,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '0252793693',
      prisonCode: 'string',
      firstName: 'Haidyn',
      lastName: 'Mathias',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 180,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '2789250366',
      prisonCode: 'string',
      firstName: 'Trysten',
      lastName: 'Hallett',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 661,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'IN_PERSON',
    visitTypeDescription: 'In Person',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 4,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '9296416563',
      prisonCode: 'string',
      firstName: 'Carnell',
      lastName: 'Braud',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 746,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'CANCELLED',
    visitStatusDescription: 'Cancelled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 4,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '4057267557',
      prisonCode: 'string',
      firstName: 'Gisella',
      lastName: 'Rushton',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 379,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 2,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '9453493566',
      prisonCode: 'string',
      firstName: 'Jamiyah',
      lastName: 'Crisp',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 995,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 8,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '8734401730',
      prisonCode: 'string',
      firstName: 'Bridgett',
      lastName: 'Halley',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 548,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Scheduled',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 3,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '4094873098',
      prisonCode: 'string',
      firstName: 'Amiya',
      lastName: 'Goldman',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 267,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'EXPIRED',
    visitStatusDescription: 'Expired',
    visitTypeCode: 'TELEPHONE',
    visitTypeDescription: 'Telephone',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 5,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '8692760551',
      prisonCode: 'string',
      firstName: 'Andi',
      lastName: 'Pick',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
  {
    officialVisitId: 137,
    prisonCode: 'MDI',
    prisonDescription: 'Moorland (HMP & YOI)',
    visitStatus: 'SCHEDULED',
    visitStatusDescription: 'Completed',
    visitTypeCode: 'UNKNOWN',
    visitTypeDescription: 'Unknown',
    visitDate: '2026-12-23',
    startTime: '10:00',
    endTime: '11:00',
    dpsLocationId: 'aaaa-bbbb-9f9f9f9f-9f9f9f9f',
    locationDescription: 'Legal visits ward',
    visitSlotId: 1,
    staffNotes: 'Legal representation details',
    prisonerNotes: 'Please arrive 10 minutes early',
    visitorConcernNotes: 'string',
    numberOfVisitors: 8,
    completionCode: 'VISITOR_CANCELLED',
    completionDescription: 'string',
    createdBy: 'Fred Bloggs',
    createdTime: '2025-12-02 14:45',
    updatedBy: 'Jane Bloggs',
    updatedTime: '22025-12-04 09:50',
    prisoner: {
      prisonerNumber: '2022615597',
      prisonCode: 'string',
      firstName: 'Stacie',
      lastName: 'Chancey',
      dateOfBirth: '2025-12-19',
      cellLocation: 'string',
      middleNames: 'string',
      offenderBookId: 0,
      attendanceCode: 'string',
      attendanceCodeDescription: 'string',
    },
  },
]
